# Generated by Django 6.0.1 on 2026-01-29 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlantTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('planted_date', models.DateField(auto_now_add=True)),
                ('height', models.FloatField(help_text='Height of the tree in meters')),
                ('tree_type', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
