# Generated by Django 6.0.1 on 2026-01-31 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treeApp', '0003_planttree_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nursery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_partnered', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NurseryPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('in_stock', models.BooleanField(default=True)),
                ('nursery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treeApp.nursery')),
            ],
        ),
        migrations.CreateModel(
            name='NurseryTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('nursery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treeApp.nursery')),
            ],
        ),
    ]
