# Generated by Django 6.0.1 on 2026-01-31 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treeApp', '0004_nursery_nurseryplant_nurserytool'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nurseryplant',
            old_name='plant_name',
            new_name='plant_type',
        ),
    ]
